/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItIndexRouteImport } from './routes/it.index'
import { Route as EsIndexRouteImport } from './routes/es.index'
import { Route as ItWorkRouteImport } from './routes/it.work'
import { Route as ItContactRouteImport } from './routes/it.contact'
import { Route as ItAboutRouteImport } from './routes/it.about'
import { Route as EsWorkRouteImport } from './routes/es.work'
import { Route as EsContactRouteImport } from './routes/es.contact'
import { Route as EsAboutRouteImport } from './routes/es.about'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItIndexRoute = ItIndexRouteImport.update({
  id: '/it/',
  path: '/it/',
  getParentRoute: () => rootRouteImport,
} as any)
const EsIndexRoute = EsIndexRouteImport.update({
  id: '/es/',
  path: '/es/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItWorkRoute = ItWorkRouteImport.update({
  id: '/it/work',
  path: '/it/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ItContactRoute = ItContactRouteImport.update({
  id: '/it/contact',
  path: '/it/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ItAboutRoute = ItAboutRouteImport.update({
  id: '/it/about',
  path: '/it/about',
  getParentRoute: () => rootRouteImport,
} as any)
const EsWorkRoute = EsWorkRouteImport.update({
  id: '/es/work',
  path: '/es/work',
  getParentRoute: () => rootRouteImport,
} as any)
const EsContactRoute = EsContactRouteImport.update({
  id: '/es/contact',
  path: '/es/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EsAboutRoute = EsAboutRouteImport.update({
  id: '/es/about',
  path: '/es/about',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/work': typeof WorkRoute
  '/es/about': typeof EsAboutRoute
  '/es/contact': typeof EsContactRoute
  '/es/work': typeof EsWorkRoute
  '/it/about': typeof ItAboutRoute
  '/it/contact': typeof ItContactRoute
  '/it/work': typeof ItWorkRoute
  '/es/': typeof EsIndexRoute
  '/it/': typeof ItIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/work': typeof WorkRoute
  '/es/about': typeof EsAboutRoute
  '/es/contact': typeof EsContactRoute
  '/es/work': typeof EsWorkRoute
  '/it/about': typeof ItAboutRoute
  '/it/contact': typeof ItContactRoute
  '/it/work': typeof ItWorkRoute
  '/es': typeof EsIndexRoute
  '/it': typeof ItIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/work': typeof WorkRoute
  '/es/about': typeof EsAboutRoute
  '/es/contact': typeof EsContactRoute
  '/es/work': typeof EsWorkRoute
  '/it/about': typeof ItAboutRoute
  '/it/contact': typeof ItContactRoute
  '/it/work': typeof ItWorkRoute
  '/es/': typeof EsIndexRoute
  '/it/': typeof ItIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/work'
    | '/es/about'
    | '/es/contact'
    | '/es/work'
    | '/it/about'
    | '/it/contact'
    | '/it/work'
    | '/es/'
    | '/it/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/work'
    | '/es/about'
    | '/es/contact'
    | '/es/work'
    | '/it/about'
    | '/it/contact'
    | '/it/work'
    | '/es'
    | '/it'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/work'
    | '/es/about'
    | '/es/contact'
    | '/es/work'
    | '/it/about'
    | '/it/contact'
    | '/it/work'
    | '/es/'
    | '/it/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  WorkRoute: typeof WorkRoute
  EsAboutRoute: typeof EsAboutRoute
  EsContactRoute: typeof EsContactRoute
  EsWorkRoute: typeof EsWorkRoute
  ItAboutRoute: typeof ItAboutRoute
  ItContactRoute: typeof ItContactRoute
  ItWorkRoute: typeof ItWorkRoute
  EsIndexRoute: typeof EsIndexRoute
  ItIndexRoute: typeof ItIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/': {
      id: '/it/'
      path: '/it'
      fullPath: '/it/'
      preLoaderRoute: typeof ItIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/': {
      id: '/es/'
      path: '/es'
      fullPath: '/es/'
      preLoaderRoute: typeof EsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/work': {
      id: '/it/work'
      path: '/it/work'
      fullPath: '/it/work'
      preLoaderRoute: typeof ItWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/contact': {
      id: '/it/contact'
      path: '/it/contact'
      fullPath: '/it/contact'
      preLoaderRoute: typeof ItContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/about': {
      id: '/it/about'
      path: '/it/about'
      fullPath: '/it/about'
      preLoaderRoute: typeof ItAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/work': {
      id: '/es/work'
      path: '/es/work'
      fullPath: '/es/work'
      preLoaderRoute: typeof EsWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/contact': {
      id: '/es/contact'
      path: '/es/contact'
      fullPath: '/es/contact'
      preLoaderRoute: typeof EsContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/about': {
      id: '/es/about'
      path: '/es/about'
      fullPath: '/es/about'
      preLoaderRoute: typeof EsAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  WorkRoute: WorkRoute,
  EsAboutRoute: EsAboutRoute,
  EsContactRoute: EsContactRoute,
  EsWorkRoute: EsWorkRoute,
  ItAboutRoute: ItAboutRoute,
  ItContactRoute: ItContactRoute,
  ItWorkRoute: ItWorkRoute,
  EsIndexRoute: EsIndexRoute,
  ItIndexRoute: ItIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
